import { IconType } from "react-icons";
import {
  RiAddLine,
  RiArrowDownSLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiArticleFill,
  RiArticleLine,
  RiChat1Line,
  RiChat3Fill,
  RiCheckboxBlankCircleLine,
  RiCheckboxCircleFill,
  RiCloseLine,
  RiDeleteBin2Line,
  RiDiscordFill,
  RiErrorWarningFill,
  RiEyeCloseLine,
  RiEyeLine,
  RiFacebookFill,
  RiFunctionFill,
  RiGoogleFill,
  RiHashtag,
  RiImage2Line,
  RiLoader5Line,
  RiLoginBoxLine,
  RiLogoutBoxFill,
  RiLogoutBoxLine,
  RiMacbookLine,
  RiMenu2Line,
  RiMoonCloudyLine,
  RiMoonFoggyLine,
  RiMore2Fill,
  RiMoreFill,
  RiPencilLine,
  RiPercentLine,
  RiSearch2Line,
  RiSearchLine,
  RiSettings2Line,
  RiSunCloudyLine,
  RiSunFoggyLine,
  RiThumbUpFill,
  RiThumbUpLine,
  RiUser2Line,
  RiUser3Line,
} from "react-icons/ri";

export const Icons = {
  User: RiUser3Line,
  Spinner: RiLoader5Line,
  Circle: RiCheckboxBlankCircleLine,
  Discord: RiDiscordFill,
  Google: RiGoogleFill,
  Facebook: RiFacebookFill,
  Logo: RiPercentLine,
  Eye: RiEyeLine,
  EyeClose: RiEyeCloseLine,
  ArrowDown: RiArrowDownSLine,
  Menu: RiMenu2Line,
  Close: RiCloseLine,
  Success: RiCheckboxCircleFill,
  Error: RiErrorWarningFill,
  Sun: RiSunFoggyLine,
  Moon: RiMoonFoggyLine,
  Macbook: RiMacbookLine,
  MoreVertical: RiMore2Fill,
  MoreHorizontal: RiMoreFill,
  Login: RiLoginBoxLine,
  Logout: RiLogoutBoxLine,
  Setting: RiSettings2Line,
  Pencil: RiPencilLine,
  Article: RiArticleLine,
  Add: RiAddLine,
  Chat: RiChat1Line,
  ThumbUpLine: RiThumbUpLine,
  ThumbUpFill: RiThumbUpFill,
  Search: RiSearchLine,
  DeleteBin: RiDeleteBin2Line,
  ArrowRightS: RiArrowRightSLine,
  ArrowLeftS: RiArrowLeftSLine,
  Image: RiImage2Line,
  Topic: RiChat3Fill,
  Hashtag: RiHashtag,
};
