import { IconType } from "react-icons";
import {
  RiAddLine,
  RiArrowDownSLine,
  RiArticleFill,
  RiArticleLine,
  RiCheckboxBlankCircleLine,
  RiCheckboxCircleFill,
  RiCloseLine,
  RiDiscordFill,
  RiErrorWarningFill,
  RiEyeCloseLine,
  RiEyeLine,
  RiFacebookFill,
  RiFunctionFill,
  RiGoogleFill,
  RiLoader5Line,
  RiLoginBoxLine,
  RiLogoutBoxFill,
  RiLogoutBoxLine,
  RiMacbookLine,
  RiMenu2Line,
  RiMoonCloudyLine,
  RiMoonFoggyLine,
  RiMore2Fill,
  RiMoreFill,
  RiPencilLine,
  RiSettings2Line,
  RiSunCloudyLine,
  RiSunFoggyLine,
  RiUser2Line,
  RiUser3Line,
} from "react-icons/ri";

export const Icons = {
  User: RiUser3Line,
  Spinner: RiLoader5Line,
  Circle: RiCheckboxBlankCircleLine,
  Discord: RiDiscordFill,
  Google: RiGoogleFill,
  Facebook: RiFacebookFill,
  Logo: RiArticleFill,
  Eye: RiEyeLine,
  EyeClose: RiEyeCloseLine,
  ArrowDown: RiArrowDownSLine,
  Menu: RiMenu2Line,
  Close: RiCloseLine,
  Success: RiCheckboxCircleFill,
  Error: RiErrorWarningFill,
  Sun: RiSunFoggyLine,
  Moon: RiMoonFoggyLine,
  Macbook: RiMacbookLine,
  MoreVertical: RiMore2Fill,
  MoreHorizontal: RiMoreFill,
  Login: RiLoginBoxLine,
  Logout: RiLogoutBoxLine,
  Setting: RiSettings2Line,
  Pencil: RiPencilLine,
  Article: RiArticleLine,
  Add: RiAddLine,
};
